source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TFCamera_Example', :exclusive => true do
  pod 'TFCamera', :path => '../'
end

target 'TFCamera_Tests', :exclusive => true do
  pod 'TFCamera', :path => '../'

  
end
